/**
 * Discovery & Audience Building Loaders
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type {
  DiscoveryContext,
  AudienceBuilderContext,
  LoaderOptions,
  LoaderResult,
} from '../types'

export async function loadDiscoveryContext(
  supabase: SupabaseClient,
  options: LoaderOptions
): Promise<LoaderResult<DiscoveryContext>> {
  const startTime = Date.now()

  try {
    // Discovery is AI-powered - would call AI service here
    // For now, return empty structure
    return {
      data: {
        similarArtists: [],
        risingScenes: [],
        suggestedAgencies: [],
        potentialCollaborators: [],
      },
      loadTime: Date.now() - startTime,
      cached: false,
    }
  } catch (error) {
    return {
      data: {
        similarArtists: [],
        risingScenes: [],
        suggestedAgencies: [],
        potentialCollaborators: [],
      },
      error: error instanceof Error ? error.message : 'Unknown error',
      loadTime: Date.now() - startTime,
      cached: false,
    }
  }
}

export async function loadAudienceBuilderContext(
  supabase: SupabaseClient,
  options: LoaderOptions
): Promise<LoaderResult<AudienceBuilderContext>> {
  const startTime = Date.now()

  try {
    const { data: suggestions } = await supabase
      .from('audience_builder_suggestions')
      .select('*')
      .eq('user_id', options.userId)
      .order('created_at', { ascending: false })
      .limit(20)

    // Load related segments
    const { data: segments } = await supabase
      .from('smart_segments')
      .select('*')
      .eq('user_id', options.userId)
      .eq('ai_generated', true)
      .order('created_at', { ascending: false })
      .limit(10)

    return {
      data: {
        suggestions:
          suggestions?.map((s) => ({
            id: s.id,
            type: s.suggestion_type || 'contact',
            contacts: s.suggested_contacts || [],
            reasoning: s.reasoning?.summary || '',
            confidenceScore: s.confidence_score || 0,
            isApplied: s.is_applied,
          })) || [],
        autoGeneratedSegments:
          segments?.map((s) => ({
            id: s.id,
            name: s.name,
            contactCount: s.contact_count || 0,
            isDynamic: s.is_dynamic,
            aiGenerated: s.ai_generated,
            lastComputed: s.last_computed_at ? new Date(s.last_computed_at) : undefined,
          })) || [],
      },
      loadTime: Date.now() - startTime,
      cached: false,
    }
  } catch (error) {
    return {
      data: {
        suggestions: [],
        autoGeneratedSegments: [],
      },
      error: error instanceof Error ? error.message : 'Unknown error',
      loadTime: Date.now() - startTime,
      cached: false,
    }
  }
}
