// This file will be auto-generated by Supabase
// Run: pnpm db:types
// Placeholder for now

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {}
    Views: {}
    Functions: {}
    Enums: {}
  }
}
