// This file will be auto-generated by Supabase
// Run: pnpm db:types
// Placeholder for now

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      [table: string]: {
        Row: Record<string, any>
        Insert: Record<string, any>
        Update: Record<string, any>
        Relationships: unknown[]
      }
    }
    Views: {
      [view: string]: {
        Row: Record<string, any>
      }
    }
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
  }
}
