import { getSupabaseClient, getSupabaseAdmin } from './client'
import { AutoChainSchema, type DbAutoChain } from './types'

/**
 * Get all auto-chains for a user
 */
export async function getAutoChains(userId: string): Promise<DbAutoChain[]> {
  const supabase = getSupabaseClient()
  const { data, error } = await supabase
    .from('auto_chains')
    .select('*')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })

  if (error) throw error
  return data.map((chain) => AutoChainSchema.parse(chain))
}

/**
 * Get a single auto-chain by ID
 */
export async function getAutoChain(id: string): Promise<DbAutoChain | null> {
  const supabase = getSupabaseClient()
  const { data, error } = await supabase.from('auto_chains').select('*').eq('id', id).single()

  if (error) {
    if (error.code === 'PGRST116') return null
    throw error
  }
  return AutoChainSchema.parse(data)
}

/**
 * Get auto-chains by chain type
 */
export async function getAutoChainsByType(
  userId: string,
  chainType: DbAutoChain['chain_type']
): Promise<DbAutoChain[]> {
  const supabase = getSupabaseClient()
  const { data, error } = await supabase
    .from('auto_chains')
    .select('*')
    .eq('user_id', userId)
    .eq('chain_type', chainType)
    .order('created_at', { ascending: false })

  if (error) throw error
  return data.map((chain) => AutoChainSchema.parse(chain))
}

/**
 * Get auto-generated chains
 */
export async function getAutoGeneratedChains(userId: string): Promise<DbAutoChain[]> {
  const supabase = getSupabaseClient()
  const { data, error } = await supabase
    .from('auto_chains')
    .select('*')
    .eq('user_id', userId)
    .eq('auto_generated', true)
    .order('confidence_score', { ascending: false })

  if (error) throw error
  return data.map((chain) => AutoChainSchema.parse(chain))
}

/**
 * Create a new auto-chain
 */
export async function createAutoChain(
  chain: Omit<DbAutoChain, 'id' | 'created_at' | 'updated_at'>
): Promise<DbAutoChain> {
  const supabase = getSupabaseAdmin()
  const { data, error } = await supabase.from('auto_chains').insert(chain).select().single()

  if (error) throw error
  return AutoChainSchema.parse(data)
}

/**
 * Update an auto-chain
 */
export async function updateAutoChain(
  id: string,
  updates: Partial<Omit<DbAutoChain, 'id' | 'user_id' | 'created_at' | 'updated_at'>>
): Promise<DbAutoChain> {
  const supabase = getSupabaseAdmin()
  const { data, error } = await supabase.from('auto_chains').update(updates).eq('id', id).select().single()

  if (error) throw error
  return AutoChainSchema.parse(data)
}

/**
 * Delete an auto-chain
 */
export async function deleteAutoChain(id: string): Promise<void> {
  const supabase = getSupabaseAdmin()
  const { error } = await supabase.from('auto_chains').delete().eq('id', id)

  if (error) throw error
}

/**
 * Add nodes to an auto-chain
 */
export async function addNodesToChain(id: string, nodeIds: string[]): Promise<DbAutoChain> {
  const chain = await getAutoChain(id)
  if (!chain) throw new Error('Auto-chain not found')

  const updatedNodes = [...chain.nodes, ...nodeIds]
  return updateAutoChain(id, { nodes: updatedNodes })
}

/**
 * Remove nodes from an auto-chain
 */
export async function removeNodesFromChain(id: string, nodeIds: string[]): Promise<DbAutoChain> {
  const chain = await getAutoChain(id)
  if (!chain) throw new Error('Auto-chain not found')

  const updatedNodes = chain.nodes.filter((nodeId) => !nodeIds.includes(nodeId))
  return updateAutoChain(id, { nodes: updatedNodes })
}
