/**
 * Default Loop Templates
 * Prebuilt sequences for quick starts
 */

import type { LoopExport } from '@/lib/exportLoop'

export const DEFAULT_LOOPS: LoopExport[] = [
  {
    version: '1.0',
    exported_at: new Date().toISOString(),
    name: 'Single Release Campaign',
    description: 'Complete workflow for releasing a single track',
    nodes: [
      {
        title: 'Finalise track master',
        description: 'Complete final mix and mastering',
        node_type: 'creative',
        status: 'pending',
        depends_on: [],
        sequence_order: 1,
        auto_start: false,
        position_x: 100,
        position_y: 100,
        momentum_value: 5,
        tags: ['creative', 'production'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Create cover artwork',
        description: 'Design release artwork (3000x3000px)',
        node_type: 'creative',
        status: 'pending',
        depends_on: [],
        sequence_order: 2,
        auto_start: false,
        position_x: 100,
        position_y: 200,
        momentum_value: 3,
        tags: ['creative', 'artwork'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Upload to distributor',
        description: 'DistroKid, CD Baby, or TuneCore',
        node_type: 'promotional',
        status: 'pending',
        depends_on: ['node-0', 'node-1'], // Will be remapped on import
        sequence_order: 3,
        auto_start: true,
        position_x: 100,
        position_y: 300,
        momentum_value: 4,
        tags: ['distribution'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Build radio contact list',
        description: 'Research and compile 50 radio contacts',
        node_type: 'planning',
        status: 'pending',
        depends_on: [],
        sequence_order: 4,
        auto_start: false,
        position_x: 300,
        position_y: 100,
        momentum_value: 3,
        tags: ['radio', 'research'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Send radio promo emails',
        description: 'Personalised pitches to radio contacts',
        node_type: 'promotional',
        status: 'pending',
        depends_on: ['node-2', 'node-3'],
        sequence_order: 5,
        auto_start: true,
        position_x: 300,
        position_y: 200,
        momentum_value: 5,
        tags: ['radio', 'promo'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Create social media plan',
        description: '4-week content calendar',
        node_type: 'planning',
        status: 'pending',
        depends_on: ['node-1'],
        sequence_order: 6,
        auto_start: false,
        position_x: 300,
        position_y: 300,
        momentum_value: 3,
        tags: ['social', 'planning'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Track campaign results',
        description: 'Monitor streams, radio plays, engagement',
        node_type: 'analysis',
        status: 'pending',
        depends_on: ['node-4', 'node-5'],
        sequence_order: 7,
        auto_start: false,
        position_x: 500,
        position_y: 200,
        momentum_value: 2,
        tags: ['analytics'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
    ],
    notes: [
      {
        title: 'Release Timeline',
        content:
          'Week 1: Finalise track + artwork\nWeek 2: Upload + build contact list\nWeek 3: Send radio promo\nWeek 4-8: Track results',
        tags: ['timeline', 'planning'],
        backlinks: [],
        linked_nodes: [],
        ai_summary: null,
        ai_themes: [],
        metadata: {},
      },
    ],
  },
  {
    version: '1.0',
    exported_at: new Date().toISOString(),
    name: 'Album Pre-Release Workflow',
    description: 'Prepare and build momentum before album release',
    nodes: [
      {
        title: 'Select 3 singles from album',
        description: 'Choose strategic singles for pre-release campaign',
        node_type: 'planning',
        status: 'pending',
        depends_on: [],
        sequence_order: 1,
        auto_start: false,
        position_x: 100,
        position_y: 100,
        momentum_value: 3,
        tags: ['planning', 'album'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Create teaser campaign',
        description: 'Short clips, behind-the-scenes content',
        node_type: 'creative',
        status: 'pending',
        depends_on: ['node-0'],
        sequence_order: 2,
        auto_start: true,
        position_x: 100,
        position_y: 200,
        momentum_value: 4,
        tags: ['creative', 'social'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Pitch to playlists',
        description: 'Target 20 Spotify + Apple Music playlists',
        node_type: 'promotional',
        status: 'pending',
        depends_on: ['node-0'],
        sequence_order: 3,
        auto_start: false,
        position_x: 100,
        position_y: 300,
        momentum_value: 5,
        tags: ['playlists', 'promo'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Build email list',
        description: 'Collect 500 fan emails pre-release',
        node_type: 'promotional',
        status: 'pending',
        depends_on: [],
        sequence_order: 4,
        auto_start: false,
        position_x: 300,
        position_y: 100,
        momentum_value: 4,
        tags: ['email', 'fanbase'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
    ],
    notes: [],
  },
  {
    version: '1.0',
    exported_at: new Date().toISOString(),
    name: 'Creative Sprint',
    description: '7-day intensive creative workflow',
    nodes: [
      {
        title: 'Day 1: Write 3 song concepts',
        description: 'Brainstorm and outline 3 different song ideas',
        node_type: 'creative',
        status: 'pending',
        depends_on: [],
        sequence_order: 1,
        auto_start: false,
        position_x: 100,
        position_y: 100,
        momentum_value: 3,
        tags: ['writing', 'creative'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Day 2-3: Produce demo tracks',
        description: 'Record rough demos for all 3 concepts',
        node_type: 'creative',
        status: 'pending',
        depends_on: ['node-0'],
        sequence_order: 2,
        auto_start: true,
        position_x: 100,
        position_y: 200,
        momentum_value: 5,
        tags: ['production', 'creative'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Day 4: Select best concept',
        description: 'Review demos and choose strongest track',
        node_type: 'analysis',
        status: 'pending',
        depends_on: ['node-1'],
        sequence_order: 3,
        auto_start: true,
        position_x: 100,
        position_y: 300,
        momentum_value: 2,
        tags: ['analysis'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
      {
        title: 'Day 5-7: Polish final track',
        description: 'Full production, mixing, and mastering',
        node_type: 'creative',
        status: 'pending',
        depends_on: ['node-2'],
        sequence_order: 4,
        auto_start: true,
        position_x: 100,
        position_y: 400,
        momentum_value: 5,
        tags: ['production', 'mastering'],
        metadata: {},
        completed_at: null,
        due_date: null,
      },
    ],
    notes: [],
  },
]
