/**
 * Creative Fingerprint Exporter
 * Phase 22: Creative Memory Graph
 *
 * Export creative fingerprints to JSON and Markdown formats (British English)
 */

import type { CreativeFingerprint, FingerprintExportOptions } from './cmg.types';

// =====================================================================
// JSON Export
// =====================================================================

/**
 * Export creative fingerprint as JSON string
 */
export function exportCreativeFingerprintJSON(fingerprint: CreativeFingerprint): string {
  return JSON.stringify(fingerprint, null, 2);
}

// =====================================================================
// Markdown Export
// =====================================================================

/**
 * Export creative fingerprint as Markdown document (British English)
 */
export function exportCreativeFingerprintMarkdown(fingerprint: CreativeFingerprint): string {
  const { structural, emotional, os, sonic, computedAt, window } = fingerprint;

  const sections: string[] = [];

  // Header
  sections.push('# Creative Fingerprint Report\n');
  sections.push(`**Computed:** ${new Date(computedAt).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  })}\n`);
  sections.push(`**Window:** ${formatWindow(window)}\n`);
  sections.push('---\n');

  // Structural Fingerprint
  sections.push('## Structural Fingerprint\n');
  sections.push(`- **Typical Arc Length:** ${Math.round(structural.typicalArcLength)} units`);
  sections.push(`- **Peak Position:** ${Math.round(structural.peakPosition * 100)}% through arc`);
  sections.push(`- **Cycle Count:** ${structural.cycleCount.toFixed(1)} rise/fall cycles`);
  sections.push(`- **Three-Act Proportion:** ${Math.round(structural.threeActProportion * 100)}%`);
  sections.push(`- **Rise Rate:** ${structural.riseRate.toFixed(2)} per day`);
  sections.push(`- **Fall Rate:** ${structural.fallRate.toFixed(2)} per day`);
  sections.push(`- **Typical Complexity:** ${structural.typicalComplexity.toFixed(1)} markers per arc\n`);

  // Emotional Fingerprint
  sections.push('## Emotional Fingerprint\n');
  sections.push('### Sentiment Distribution');
  sections.push(`- **Positive:** ${Math.round(emotional.positiveRatio * 100)}%`);
  sections.push(`- **Negative:** ${Math.round(emotional.negativeRatio * 100)}%`);
  sections.push(`- **Neutral:** ${Math.round(emotional.neutralRatio * 100)}%`);
  sections.push(`- **Mixed:** ${Math.round(emotional.mixedRatio * 100)}%\n`);
  sections.push('### Emotional Patterns');
  sections.push(`- **Typical Resolution:** ${formatResolutionPattern(emotional.typicalResolutionPattern)}`);
  sections.push(`- **Volatility:** ${formatVolatility(emotional.volatility)} (${Math.round(emotional.volatility * 100)}%)`);
  sections.push(`- **Resolution Tendency:** ${Math.round(emotional.resolutionTendency * 100)}%\n`);

  // OS Fingerprint
  sections.push('## OS Fingerprint\n');
  sections.push(`- **Dominant OS:** ${os.dominantOS?.toUpperCase() || 'None'}`);
  sections.push(`- **Resolution OS:** ${os.resolutionOS?.toUpperCase() || 'None'}`);
  sections.push(`- **Tension OS:** ${os.tensionOS?.toUpperCase() || 'None'}`);
  sections.push(`- **Lead OS:** ${os.leadOS?.toUpperCase() || 'None'}\n`);
  sections.push('### OS Distribution');
  Object.entries(os.osDistribution).forEach(([osName, count]) => {
    if (count > 0) {
      sections.push(`- **${osName.toUpperCase()}:** ${count} nodes`);
    }
  });
  sections.push('');

  // Sonic Fingerprint
  sections.push('## Sonic Fingerprint\n');
  sections.push(`- **Typical Tempo Range:** ${Math.round(sonic.typicalTempoRange[0])}–${Math.round(sonic.typicalTempoRange[1])} BPM`);
  sections.push(`- **Typical Density:** ${Math.round(sonic.typicalDensity * 100)}%`);
  sections.push(`- **Harmonic Palette:** ${capitalise(sonic.harmonicPalette)}`);
  sections.push(`- **Dynamic Range:** ${Math.round(sonic.dynamicRange * 100)}%`);
  sections.push(`- **Timbral Preference:** ${capitalise(sonic.timbralPreference)}\n`);

  // Footer
  sections.push('---\n');
  sections.push('*This report was generated by the Creative Memory Graph system.*\n');

  return sections.join('\n');
}

/**
 * Export fingerprint summary as concise Markdown (British English)
 */
export function exportFingerprintSummaryMarkdown(fingerprint: CreativeFingerprint): string {
  const { structural, emotional, os, sonic } = fingerprint;

  const sections: string[] = [];

  sections.push('# Creative Fingerprint Summary\n');

  // Key insights
  sections.push('## Key Insights\n');

  // Structural insight
  const arcType =
    structural.peakPosition < 0.4
      ? 'early-peak'
      : structural.peakPosition > 0.7
        ? 'late-peak'
        : 'classic three-act';
  sections.push(`- Your work typically follows a **${arcType}** structure`);

  // Emotional insight
  const dominantSentiment =
    emotional.positiveRatio > 0.4
      ? 'optimistic'
      : emotional.negativeRatio > 0.4
        ? 'realistic'
        : 'balanced';
  sections.push(`- Your emotional style tends towards **${dominantSentiment}** narratives`);

  // OS insight
  if (os.leadOS) {
    sections.push(`- **${os.leadOS.toUpperCase()}** OS typically leads your campaigns`);
  }

  // Sonic insight
  const tempoBand = `${Math.round(sonic.typicalTempoRange[0])}–${Math.round(sonic.typicalTempoRange[1])} BPM`;
  sections.push(`- Your typical tempo range is **${tempoBand}** (${sonic.harmonicPalette} palette)`);

  sections.push('');

  return sections.join('\n');
}

// =====================================================================
// Helper Functions
// =====================================================================

function formatWindow(window: string): string {
  if (window === 'lifetime') return 'All time';

  const match = window.match(/^(\d+)([dwmy])$/);
  if (!match) return window;

  const value = match[1];
  const unit = match[2];

  const unitMap = {
    d: 'day',
    w: 'week',
    m: 'month',
    y: 'year',
  };

  const unitName = unitMap[unit as keyof typeof unitMap] || unit;
  const plural = parseInt(value) !== 1 ? 's' : '';

  return `Last ${value} ${unitName}${plural}`;
}

function formatResolutionPattern(pattern: string): string {
  const labels = {
    positive: 'Optimistic (tends to positive outcomes)',
    negative: 'Realistic (tends to negative outcomes)',
    neutral: 'Balanced (tends to neutral outcomes)',
    ambiguous: 'Complex (mixed outcomes)',
  };

  return labels[pattern as keyof typeof labels] || pattern;
}

function formatVolatility(volatility: number): string {
  if (volatility > 0.7) return 'High';
  if (volatility > 0.4) return 'Moderate';
  return 'Low';
}

function capitalise(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

// =====================================================================
// Unified Export Function
// =====================================================================

/**
 * Export creative fingerprint in specified format
 */
export function exportCreativeFingerprint(
  fingerprint: CreativeFingerprint,
  options: FingerprintExportOptions
): string {
  const { format, includeSummary } = options;

  if (format === 'json') {
    return exportCreativeFingerprintJSON(fingerprint);
  }

  if (format === 'markdown') {
    if (includeSummary) {
      const full = exportCreativeFingerprintMarkdown(fingerprint);
      const summary = exportFingerprintSummaryMarkdown(fingerprint);
      return `${summary}\n\n---\n\n${full}`;
    }
    return exportCreativeFingerprintMarkdown(fingerprint);
  }

  throw new Error(`Unsupported export format: ${format}`);
}
