-- LoopOS Persistence Tables
-- Phase 25: LoopOS AI + Persistence Engine v1

create table if not exists public.loopos_loops (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'My Loop',
  bpm integer not null default 120,
  zoom double precision not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_loopos_loops_user_id
  on public.loopos_loops(user_id);

alter table public.loopos_loops enable row level security;

create policy "Users can select their own loops"
  on public.loopos_loops
  for select
  using (auth.uid() = user_id);

create policy "Users can insert their own loops"
  on public.loopos_loops
  for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own loops"
  on public.loopos_loops
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own loops"
  on public.loopos_loops
  for delete
  using (auth.uid() = user_id);

create trigger loopos_loops_updated_at
  before update on public.loopos_loops
  for each row
  execute function public.handle_updated_at();

comment on table public.loopos_loops is 'Top-level LoopOS loops per user (Phase 25)';

create table if not exists public.loopos_clips (
  id uuid primary key default gen_random_uuid(),
  loop_id uuid not null references public.loopos_loops(id) on delete cascade,
  lane text not null,
  start double precision not null,
  length double precision not null,
  name text not null,
  notes text not null,
  loopos_ready boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_loopos_clips_loop_id
  on public.loopos_clips(loop_id);

create index if not exists idx_loopos_clips_lane
  on public.loopos_clips(lane);

alter table public.loopos_clips enable row level security;

create policy "Users can select clips for their loops"
  on public.loopos_clips
  for select
  using (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_clips.loop_id
        and l.user_id = auth.uid()
    )
  );

create policy "Users can insert clips into their loops"
  on public.loopos_clips
  for insert
  with check (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_clips.loop_id
        and l.user_id = auth.uid()
    )
  );

create policy "Users can update clips in their loops"
  on public.loopos_clips
  for update
  using (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_clips.loop_id
        and l.user_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_clips.loop_id
        and l.user_id = auth.uid()
    )
  );

create policy "Users can delete clips from their loops"
  on public.loopos_clips
  for delete
  using (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_clips.loop_id
        and l.user_id = auth.uid()
    )
  );

create trigger loopos_clips_updated_at
  before update on public.loopos_clips
  for each row
  execute function public.handle_updated_at();

comment on table public.loopos_clips is 'Clips belonging to LoopOS loops (Phase 25)';

-- Optional: LoopOS insights generated by AI

create table if not exists public.loopos_insights (
  id uuid primary key default gen_random_uuid(),
  loop_id uuid not null references public.loopos_loops(id) on delete cascade,
  generated_at timestamptz not null default now(),
  insights_json jsonb not null
);

create index if not exists idx_loopos_insights_loop_id
  on public.loopos_insights(loop_id);

alter table public.loopos_insights enable row level security;

create policy "Users can select insights for their loops"
  on public.loopos_insights
  for select
  using (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_insights.loop_id
        and l.user_id = auth.uid()
    )
  );

create policy "Users can insert insights for their loops"
  on public.loopos_insights
  for insert
  with check (
    exists (
      select 1
      from public.loopos_loops l
      where l.id = loopos_insights.loop_id
        and l.user_id = auth.uid()
    )
  );

comment on table public.loopos_insights is 'AI-generated insights for LoopOS loops (Phase 25)';


