import type { CampaignData, EPKData, BriefData } from '../types'

/**
 * HTML Exporter
 *
 * Generates HTML documents from campaign/EPK/brief data.
 */

export function exportCampaignToHTML(data: CampaignData): string {
  return `<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.name} - Campaign Report</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 { color: #3AA9BE; margin-bottom: 0.5em; }
    h2 { color: #2a2a2a; margin-top: 2em; border-bottom: 2px solid #3AA9BE; padding-bottom: 0.3em; }
    .node { background: #f5f5f5; padding: 15px; margin: 10px 0; border-left: 4px solid #3AA9BE; }
    .node-title { font-weight: bold; margin-bottom: 5px; }
    .node-status { display: inline-block; padding: 2px 8px; border-radius: 3px; font-size: 0.85em; }
    .status-completed { background: #4caf50; color: white; }
    .status-active { background: #ff9800; color: white; }
    .status-pending { background: #9e9e9e; color: white; }
    .journal-entry { background: #fafafa; padding: 15px; margin: 10px 0; border-left: 4px solid #999; }
    .insights { background: #e3f2fd; padding: 20px; border-radius: 8px; margin: 20px 0; }
    .metric { display: inline-block; margin-right: 30px; }
    .metric-value { font-size: 2em; font-weight: bold; color: #3AA9BE; }
    .metric-label { font-size: 0.9em; color: #666; }
  </style>
</head>
<body>
  <h1>${data.name}</h1>
  <p><strong>Created:</strong> ${new Date(data.createdAt).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })}</p>

  <h2>Campaign Nodes</h2>
  ${data.nodes
    .map(
      (node) => `
    <div class="node">
      <div class="node-title">${node.title}</div>
      <div>${node.description || ''}</div>
      <span class="node-status status-${node.status}">${node.status}</span>
    </div>
  `
    )
    .join('')}

  ${
    data.insights
      ? `
  <h2>Insights</h2>
  <div class="insights">
    <div class="metric">
      <div class="metric-value">${data.insights.flowScore}</div>
      <div class="metric-label">Flow Score</div>
    </div>
    <div class="metric">
      <div class="metric-value">${data.insights.momentum}</div>
      <div class="metric-label">Momentum</div>
    </div>
    <div class="metric">
      <div class="metric-value">${data.insights.completedNodes}</div>
      <div class="metric-label">Completed Nodes</div>
    </div>
  </div>
  `
      : ''
  }

  ${
    data.journalEntries
      ? `
  <h2>Journal Entries</h2>
  ${data.journalEntries
    .map(
      (entry) => `
    <div class="journal-entry">
      <p>${entry.content}</p>
      <small>${new Date(entry.created_at).toLocaleDateString('en-GB')}</small>
    </div>
  `
    )
    .join('')}
  `
      : ''
  }

  <footer style="margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999; font-size: 0.9em;">
    <p>Generated by LoopOS • ${new Date().toLocaleDateString('en-GB')}</p>
  </footer>
</body>
</html>`
}

export function exportEPKToHTML(data: EPKData): string {
  return `<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.artistName} - ${data.projectName} EPK</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 { font-size: 3em; margin-bottom: 0.2em; }
    h2 { color: #3AA9BE; margin-top: 2em; }
    .bio { font-size: 1.1em; line-height: 1.8; margin: 20px 0; }
    .links a { display: inline-block; margin-right: 15px; color: #3AA9BE; text-decoration: none; }
    .tracks { list-style: none; padding: 0; }
    .tracks li { padding: 10px; background: #f5f5f5; margin: 5px 0; }
  </style>
</head>
<body>
  <h1>${data.artistName}</h1>
  <h2>${data.projectName}</h2>
  ${data.releaseDate ? `<p><strong>Release Date:</strong> ${data.releaseDate}</p>` : ''}

  <div class="bio">
    <h2>Bio</h2>
    <p>${data.bio}</p>
  </div>

  ${
    data.tracks.length > 0
      ? `
  <h2>Tracks</h2>
  <ul class="tracks">
    ${data.tracks.map((track) => `<li>${track}</li>`).join('')}
  </ul>
  `
      : ''
  }

  <h2>Links</h2>
  <div class="links">
    ${data.links.spotify ? `<a href="${data.links.spotify}">Spotify</a>` : ''}
    ${data.links.apple ? `<a href="${data.links.apple}">Apple Music</a>` : ''}
    ${data.links.bandcamp ? `<a href="${data.links.bandcamp}">Bandcamp</a>` : ''}
    ${data.links.instagram ? `<a href="${data.links.instagram}">Instagram</a>` : ''}
    ${data.links.website ? `<a href="${data.links.website}">Website</a>` : ''}
  </div>

  ${
    data.forFansOf && data.forFansOf.length > 0
      ? `
  <h2>For Fans Of</h2>
  <p>${data.forFansOf.join(', ')}</p>
  `
      : ''
  }

  <footer style="margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999;">
    <p>Generated by LoopOS • ${new Date().toLocaleDateString('en-GB')}</p>
  </footer>
</body>
</html>`
}

export function exportBriefToHTML(data: BriefData): string {
  const briefTitles = {
    pr: 'PR Brief',
    radio: 'Radio Brief',
    social: 'Social Media Brief',
  }

  return `<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${data.artistName} - ${briefTitles[data.briefType]}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #333;
    }
    h1 { color: #3AA9BE; }
    h2 { color: #2a2a2a; margin-top: 2em; }
    ul { padding-left: 20px; }
    li { margin: 10px 0; }
    .highlight { background: #e3f2fd; padding: 15px; border-left: 4px solid #3AA9BE; margin: 15px 0; }
  </style>
</head>
<body>
  <h1>${briefTitles[data.briefType]}</h1>
  <h2>${data.artistName} - ${data.projectName}</h2>

  <div class="highlight">
    <p><strong>Genre:</strong> ${data.genre}</p>
    ${data.releaseDate ? `<p><strong>Release Date:</strong> ${data.releaseDate}</p>` : ''}
    <p><strong>Timeline:</strong> ${data.timeline}</p>
  </div>

  <h2>Key Angles</h2>
  <ul>
    ${data.keyAngles.map((angle) => `<li>${angle}</li>`).join('')}
  </ul>

  <h2>Target Audience</h2>
  <p>${data.targetAudience}</p>

  <h2>Objectives</h2>
  <ul>
    ${data.objectives.map((obj) => `<li>${obj}</li>`).join('')}
  </ul>

  <footer style="margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #999;">
    <p>Generated by LoopOS • ${new Date().toLocaleDateString('en-GB')}</p>
  </footer>
</body>
</html>`
}
